name: Otomatik Veri Guncelleme

on:
  schedule:
    - cron: '0 */6 *6 *' # Her 6 saatte bir çalışır
  workflow_dispatch: # El ile de tetiklenebilir

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Depoyu Kopyala
        uses: actions/checkout@v3

      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Kütüphaneleri Yükle
        run: pip install -r requirements.txt

      - name: Python Kodunu Çalıştır
        run: python guncelle.py

      - name: Değişiklikleri Kaydet ve Gönder
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add oyuncular.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Otomatik skor güncellemesi" && git push)
